name: 🐛 Bug Report
description: Report a broken command, smaller issue, or something not working
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: What went wrong?
      description: Describe the issue clearly.
      placeholder: "The start command did not work..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: How dod it happen?
      placeholder: "do not simply enter it didnt work"
  - type: input
    attributes:
      label: Device
      description: Whether this is an issue on your side
